heat_template_version: 2013-05-23

description: >
  Based on Heat Wordpress example

parameters:
  mariadb_image:
    type: string
    description: The mariadb image
    default: mariadb
  wordpress_image:
    type: string
    description: The wordpress image
    default: wordpress
  flavor:
    type: string
    description: Flavor to use for the WordPress server.
    constraints:
      - custom_constraint: nova.flavor
    default: m1.medium
  MysqlRootPassword:
    type: string
    default: root

resources:
  Wordpress_auth_string:
    type: OS::Heat::RandomString

  Wordpress_db_password:
    type: OS::Heat::RandomString

  Mariadb:
    type: OS::Nova::Server
    properties:
      image: { get_param: mariadb_image }
      flavor: { get_param: flavor }
      user_data_format: SOFTWARE_CONFIG
      key_name: goneri

  MariadbConfig:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        wordpress_db:
          password: {get_resource: Wordpress_db_password}
          host: {get_attr: [Wordpress, first_address]}

  MariadbDeployment:
    type: OS::Heat::StructuredDeployment
    properties:
      signal_transport: NO_SIGNAL
      config: {get_resource: MariadbConfig}
      server: {get_resource: Mariadb}

  Wordpress:
    type: OS::Nova::Server
    properties:
      image: { get_param: wordpress_image }
      flavor: { get_param: flavor }
      user_data_format: SOFTWARE_CONFIG
      key_name: goneri

  WordpressConfig:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        wordpress:
          db_name: wordpress
          db_user: wordpress
          db_password: {get_resource: Wordpress_db_password}
          db_host: {get_attr: [Mariadb, first_address]}
          auth_string: {get_attr: [Wordpress_auth_string, value]}

  WordpressDeployment:
    type: OS::Heat::StructuredDeployment
    properties:
      signal_transport: NO_SIGNAL
      config: {get_resource: WordpressConfig}
      server: {get_resource: Wordpress}

outputs:
  wordpress_url:
    description: The URL to Wordpress
    value:
      str_replace:
        template: http://host/wordpress/
        params:
          host: { get_attr: [ Wordpress, first_address ] }
  install_url:
    description: The URL to log into the deploy the application
    value:
      str_replace:
        template: http://host/wordpress/wp-admin/install.php
        params:
          host: { get_attr: [ Wordpress, first_address ] }